analyzing_queries = [
    "women's health",
    "uterus",
    "trimester",
    "menstruation",
    "menstrual",
    "cervix",
    "cervical",
    "ovaries",
    "ovarian",
    "endometrium",
    "birth control",
    "abortion",
    "pelvic exam",
    "episiotomy",
    "mastectomy",
    "braxton hicks",
    "yeast infection",
    "mammography",
    "intrauterine",
    "miscarriage",
    "menopause",
    "ovulation",
    "placenta",
    "postpartum",
    "hysterectomy",
    "perimenopause",
    "perineum",
    "eclampsia",
    "preeclampsia",
    "labor",
    "obstetric",
    "pregnancy",
    "vulva",
    "uterine",
    "fallopian",
    "breast",
    "mammary",
    "vagina",
    "labia",
    "clitoris",
    "urinary tract infection"
    ]

identifying_queries = [
    "alzheimer's disease",
    "parkinson's disease",
    "stroke",
    "coronary heart disease",
    "hypertension",
    "myocardial infarction heart attack",
    "diabetes",
    "atherosclerosis",
    "acute coronary syndrome acd",
    "asthma",
    "bronchitis",
    "emphysema"
    "cystic fibrosis",
    "lung cancer",
    "kidney disease",
    "ureteral obstruction",
    "peptic ulcer",
    "ibs",
    "ibd",
    "colorectal cancer",
    "multiple sclerosis ms",
    "osteoporosis",
    "adhd",
    "lupus",
    "sleep apnea",
    "fibromyalgia"
]